services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        REGISTRY_IMAGE: ${REGISTRY_IMAGE}
    image: ${REGISTRY_IMAGE}:${VERSION_TAG}_base

  aws:
    build:
      context: .
      dockerfile: Dockerfile.aws
      args:
        BASE_VERSION: ${VERSION_TAG}
        REGISTRY_IMAGE: ${REGISTRY_IMAGE}
    image: ${REGISTRY_IMAGE}:${VERSION_TAG}_aws
    depends_on:
      - base

  azure:
    build:
      context: .
      dockerfile: Dockerfile.azure
      args:
        BASE_VERSION: ${VERSION_TAG}
        REGISTRY_IMAGE: ${REGISTRY_IMAGE}
    image: ${REGISTRY_IMAGE}:${VERSION_TAG}_azure
    depends_on:
      - base
  
