name: Deploy - Docker Image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  prepare:
    name: Set version and build args
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_output.outputs.version }}
      is_semver: ${{ steps.set_output.outputs.is_semver }}
    steps:
        - name: Check out the repo
          uses: actions/checkout@v5
        - name: Set image tag
          id: set_output
          run: |
            ref="${GITHUB_REF##*/}"
            if [[ "$ref" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "version=$ref" >> $GITHUB_OUTPUT
              echo "is_semver=true" >> $GITHUB_OUTPUT
            else
            echo "version=$ref-${{ github.run_number }}" >> $GITHUB_OUTPUT
            fi

  buildpush:
    name: Build ➡️ Push
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: dockerhub
    env:
      REGISTRY: rooibos75
      IMAGE_NAME: devops-toolkit
      IMAGE_TAG: ${{ needs.prepare.outputs.version }}
      IS_SEMVER: ${{ needs.prepare.outputs.is_semver }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          export BUILD_ARGS=$(jq -c '.' versions.json)
          docker buildx create --use --name xbuilder
          docker buildx bake --print
          docker buildx bake --progress plain -f docker-bake.hcl --push

