name: Deploy - Docker Image Latest (main)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - '.github/workflows/*'

jobs:
  buildpush:
    name: Build ➡️ Push
    runs-on: ubuntu-latest
    env:
      REGISTRY_IMAGE: rooibos75/devops-toolkit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - id: get_version
        uses: baileyherbert/version-action@v3

      - name: Build the Docker image
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          docker buildx create --use --name xbuilder 
          docker buildx build -f Dockerfile.base --progress plain --push -t ${REGISTRY_IMAGE}:${VERSION_TAG}_base \
            --cache-to type=registry,ref=${REGISTRY_IMAGE}:build-cache \
            --cache-from type=registry,ref=${REGISTRY_IMAGE}:build-cache \
            --build-arg REGISTRY_IMAGE=${REGISTRY_IMAGE} \
            --build-arg BASE_VERSION=${VERSION_TAG} \
            .
          for dockerfile in "Dockerfile.aws" "Dockerfile.azure"; do
            suffix=$(echo $dockerfile | cut -d'.' -f2)
            echo "Building image for $suffix"
            docker buildx build -f $dockerfile --progress plain --push -t ${REGISTRY_IMAGE}:${VERSION_TAG}_$suffix \
              --build-arg REGISTRY_IMAGE=${REGISTRY_IMAGE} \
              --build-arg BASE_VERSION=${VERSION_TAG} \
              .
          done

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${REGISTRY_IMAGE}
          enable-url-completion: true
