name: Deploy - Docker Image Latest (main)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - '.github/workflows/*'

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    environment: dockerhub
    env:
      REGISTRY_IMAGE: rooibos75/devops-toolkit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - id: get_version
        uses: baileyherbert/version-action@v3

      - name: Build the Docker image
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          docker compose -f docker-compose.yaml build

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${REGISTRY_IMAGE}
          enable-url-completion: true
